name: gaussian_surfels
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile
  - python=3.7.13
  - pip=22.3.1
  # - pytorch=1.12.1
  # - torchaudio=0.12.1
  # - torchvision=0.13.1
  # - pytorch=1.12.1
  # - torchaudio=0.12.1
  # - torchvision=0.13.1
  - tqdm
  - pip:
    # 額外pip
    - torch==1.12.1+cu116 
    - torchvision==0.13.1+cu116
    - torchaudio==0.12.1
    - -f https://download.pytorch.org/whl/torch_stable.html
    # 額外pip
    - torch==1.12.1+cu116 
    - torchvision==0.13.1+cu116
    - torchaudio==0.12.1
    - -f https://download.pytorch.org/whl/torch_stable.html
    - pymeshlab
    - opencv-python
    - matplotlib
    - imageio
    - scikit-image
    - numba
    - open3d
    - trimesh
    - "git+https://github.com/facebookresearch/pytorch3d.git"
    # 另外安裝
    # - submodules/diff-gaussian-rasterization
    # - submodules/simple-knn
    # 另外安裝
    # - submodules/diff-gaussian-rasterization
    # - submodules/simple-knn
